	<script src="<?php echo $this->getSkinUrl('js/vendors/jquery.1.9.1.js'); ?>"></script>

	<script src="<?php echo $this->getSkinUrl('js/bootstrap/transition.js'); ?>"></script>
	<script src="<?php echo $this->getSkinUrl('js/bootstrap/alert.js'); ?>"></script>
	<script src="<?php echo $this->getSkinUrl('js/bootstrap/modal.js'); ?>"></script>
	<script src="<?php echo $this->getSkinUrl('js/bootstrap/dropdown.js'); ?>"></script>
	<script src="<?php echo $this->getSkinUrl('js/bootstrap/scrollspy.js'); ?>"></script>
	<script src="<?php echo $this->getSkinUrl('js/bootstrap/tab.js'); ?>"></script>
	<script src="<?php echo $this->getSkinUrl('js/bootstrap/tooltip.js'); ?>"></script>
	<script src="<?php echo $this->getSkinUrl('js/bootstrap/popover.js'); ?>"></script>
	<script src="<?php echo $this->getSkinUrl('js/bootstrap/button.js'); ?>"></script>
	<script src="<?php echo $this->getSkinUrl('js/bootstrap/collapse.js'); ?>"></script>
	<script src="<?php echo $this->getSkinUrl('js/bootstrap/carousel.js'); ?>"></script>
	<script src="<?php echo $this->getSkinUrl('js/bootstrap/affix.js'); ?>"></script>
	<script src="<?php echo $this->getSkinUrl('js/bootstrap/transition.js'); ?>"></script>
	<script src="<?php echo $this->getSkinUrl('js/main.js'); ?>"></script>
	<script type="text/javascript">
		$.noConflict();
		jQuery(document).ready(function($) {
			// Code that uses jQuery's $ can follow here.
			$('.nav-collapse').on('hidden', function () {
				$('.nav-collapse').show();
			})
		});
		// Code that uses other library's $ can follow here.
	</script>
	<script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>